sudo: required
services:
  - docker

before_install:
  - docker build -t just4docker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true just4docker/react-test npm test

after_success:
  - docker build -t just4docker/multi-client ./client
  - docker build -t just4docker/multi-nginx ./nginx
  - docker build -t just4docker/multi-server ./server
  - docker build -t just4docker/multi-worker ./worker
  #Log into docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push just4docker/multi-client
  - docker push just4docker/multi-nginx
  - docker push just4docker/multi-server
  - docker push just4docker/multi-worker
#deploy:
  #edge: true
  #provider: elasticbeanstalk
  #region:
  #app:
  #env:
  #bucket_name:
  #bucket_path:
  #on:
    #branch: master
  #access_key: $AWS_ACCESS_KEY
  #secret_access_key:
    #secure: $AWS_SECRET_KEY